import type { LogoLibraryItem } from '../types';

export const LOGO_LIBRARY: LogoLibraryItem[] = [
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", label: "React" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg", label: "JavaScript" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg", label: "TypeScript" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg", label: "Python" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg", label: "Node.js" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg", label: "Vue.js" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angular/angular-original.svg", label: "Angular" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg", label: "Svelte" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg", label: "Next.js" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nuxtjs/nuxtjs-original.svg", label: "Nuxt.js" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg", label: "Express" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg", label: "FastAPI" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg", label: "Django" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg", label: "Flask" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg", label: "Spring" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-plain.svg", label: "Laravel" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rails/rails-original-wordmark.svg", label: "Rails" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg", label: "Docker" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg", label: "Kubernetes" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-original.svg", label: "Jenkins" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg", label: "Terraform" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ansible/ansible-original.svg", label: "Ansible" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg", label: "Git" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg", label: "GitHub" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg", label: "GitLab" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bitbucket/bitbucket-original.svg", label: "Bitbucket" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg", label: "AWS" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg", label: "Azure" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg", label: "Google Cloud" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/digitalocean/digitalocean-original.svg", label: "DigitalOcean" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/heroku/heroku-original.svg", label: "Heroku" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vercel/vercel-original.svg", label: "Vercel" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/netlify/netlify-original.svg", label: "Netlify" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg", label: "Firebase" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/supabase/supabase-original.svg", label: "Supabase" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg", label: "MongoDB" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg", label: "PostgreSQL" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg", label: "MySQL" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg", label: "Redis" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elasticsearch/elasticsearch-original.svg", label: "Elasticsearch" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg", label: "GraphQL" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg", label: "Figma" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sketch/sketch-original.svg", label: "Sketch" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg", label: "Photoshop" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg", label: "VS Code" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webstorm/webstorm-original.svg", label: "WebStorm" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vim/vim-original.svg", label: "Vim" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg", label: "Sass" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg", label: "Tailwind CSS" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg", label: "Bootstrap" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg", label: "Material UI" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webpack/webpack-original.svg", label: "Webpack" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vitejs/vitejs-original.svg", label: "Vite" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/babel/babel-original.svg", label: "Babel" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/eslint/eslint-original.svg", label: "ESLint" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg", label: "Jest" },
  { value: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cypress/cypress-original.svg", label: "Cypress" },
  { value: "https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/claude-ai-icon.png", label: "Claude AI" },
];